name: test_repo_example
description: "Single page Flutter app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: ^8.0.3

  # Logging
  logger: ^2.5.0

  # UI
  google_fonts: ^6.2.1
  sizer: ^3.1.3

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  dio: ^5.9.1

  freezed_annotation: ^2.4.4
  envied: ^1.1.1
  bloc_concurrency: ^0.3.0
  path_provider: ^2.1.5
  sembast: ^3.8.5+2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree-Black.ttf
          weight: 900
